version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
       uvicorn:
          patterns:
            - "uvicorn"
       dependencies:
          patterns:
            - "*"
          exclude-patterns:
            - "uvicorn"
