version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    package-rules:
      - package-names: ["*"]
        group:
          package-names: ["*"]
