name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Start Uvicorn server
      run: uvicorn main:app --host 0.0.0.0 --port 8000 &

    - name: Wait for Uvicorn to start
      run: sleep 10

    - name: Run tests
      run: pytest
